# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "jhcook/fedora25"
  config.vm.provider "virtualbox" do |vb|
  vb.gui = true
  vb.memory = 2048
  vb.customize ["modifyvm", :id, "--cpuexecutioncap", "70"]
  vb.cpus = 2
  vb.name = "mkl_messy_clean2"
end
config.vm.provision "shell", inline: <<-SHELL
  cp -a /vagrant/workspace/. /home/vagrant/Documents
  sudo dnf -y -v install openssl-devel libxml2-devel
  sudo dnf -y -v install libcurl libcurl-devel
  sudo dnf -y -v install perl-CPAN
  sudo dnf -y -v install ruby
  wget https://atom.io/download/rpm
  mv ./rpm ./atom.rpm
  sudo dnf -y -v install ./atom.rpm
  rm -rf ./atom.rpm
  sudo dnf -y -v install R-3.4.0
  sudo dnf -y -v install R
  sudo su - -c "R -e \\\"install.packages('devtools', repos='http://cran.rstudio.com/', dependencies = TRUE)\\\""
  sudo su - -c "R -e \\\"require('devtools');install_version('gdata', version='2.18.0', repos='http://cran.rstudio.com/')\\\""
  sudo su - -c "R -e \\\"require('devtools');install_version('lattice', version='0.20-35', repos='http://cran.rstudio.com/')\\\""
  sudo su - -c "R -e \\\"require('devtools');install_version('permute', version='0.9-4', repos='http://cran.rstudio.com/')\\\""
  sudo su - -c "R -e \\\"require('devtools');install_version('txtplot', version='1.0-3', repos='http://cran.rstudio.com/')\\\""
  sudo su - -c "R -e \\\"require('devtools');install_version('vegan', version='2.4-3', repos='http://cran.rstudio.com/')\\\""
 https://download1.rstudio.org/rstudio-1.0.143-x86_64.rpm
  sudo dnf -y -v install ./rstudio-1.0.143-x86_64.rpm
  rm -rf ./rstudio-1.0.143-x86_64.rpm
SHELL
end
